### ISSUE TITLE
Svg Support through Avalonia.Svg.Skia

### ISSUE THREAD

**Issue by Evelios** [fsprojects/Avalonia.FuncUI#198]
First off, is there any intention to support loading SVG files through this repository? I know that Avalonia is based off of Skia for it's rendering engine and adding support for SVG's will most likely add two new dependencies `Avalonia.Svg.Skia` and implicitly `Svg.Skia`. 

I have been trying to create a basic DSL over this library to get my svg files rendered but I'm running into an issue I'm not sure how to fix. I was following examples like the [Image DSL](https://github.com/fsprojects/Avalonia.FuncUI/blob/master/src/Avalonia.FuncUI.DSL/Image.fs) to create the wrapper. I'm starting with the bare minimum of what I think is needed to create it.

__DSL__
```fsharp
namespace Avalonia.FuncUI.DSL

module Svg =
    open Avalonia.FuncUI.Builder
    open Avalonia.FuncUI.Types
    open Avalonia.Svg.Skia

    let create (attrs: IAttr<Svg> list) : IView<Svg> = ViewBuilder.Create<Svg>(attrs)
    
    type Svg with
        static member path<'t when 't :> Svg>(path: string) : IAttr<'t> =
            AttrBuilder<'t>
                .CreateProperty<string>(Svg.PathProperty, path, ValueNone)
```

__Application__
```fsharp
module Icon =
    open Avalonia.FuncUI.DSL
    open Avalonia.Svg.Skia
    
    let svgIcon (name: string) =
        Svg.create [ Svg.path $"Assets/{name}.svg" ]
```

but I'm encountering the following runtime exception

__Exception__
```log
Unhandled exception. System.TypeLoadException: Method 'CreateTrayIcon' in type 'Avalonia.X11.AvaloniaX11Platform' from assembly 'Avalonia.X11, Version=0.10.0.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b' does not have an implementation.
   at Avalonia.AvaloniaX11PlatformExtensions.<>c__0`1.<UseX11>b__0_0()
   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 303
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 179
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 208
   at Gui.Program.main(String[] args) in Gui/Program.fs:line 29
```
__Gui/Program.fs__
```fsharp
module Program =

    [<EntryPoint>]
    let main (args: string []) =
        AppBuilder.Configure<App>()
            .UsePlatformDetect()  // Line 29
            .UseSkia()
            .StartWithClassicDesktopLifetime(args)
```

__Packages__
![image](https://user-images.githubusercontent.com/12739352/159514110-776e51ca-1514-4d5f-85a1-267f859a8542.png)

Tested on
* Ubuntu 20.04.4 LTS 64x
* macOS Monterey 12.2.1

**Comment by Evelios** [comment]
So it looks like that particular error was fixed by upgrading `Avalonia.Desktop` to `0.10.12` but it was traded out for another error. This one is looking more like an Avalonia error than the first.

* [Minimum reproducible example](https://github.com/Evelios/avalonia-funui-svg-mre)

__Exception__
```log
Unhandled exception. System.MissingMethodException: Cannot dynamically create an instance of type 'Avalonia.Svg.Skia.Svg'. Reason: No parameterless constructor defined.
   at System.RuntimeType.ActivatorCache..ctor(RuntimeType rt)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type)
   at Avalonia.FuncUI.VirtualDom.Patcher.create(ViewDelta viewElement)
   at Avalonia.FuncUI.VirtualDom.Patcher.patch_IList@86-1.Invoke(Int32 index, ViewDelta viewElement)
   at Microsoft.FSharp.Collections.SeqModule.IterateIndexed[T](FSharpFunc`2 action, IEnumerable`1 source) in D:\a\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 523
   at Avalonia.FuncUI.VirtualDom.Patcher.patch_IList@82(FSharpList`1 delta, IList collection)
   at Avalonia.FuncUI.VirtualDom.Patcher.patch(IControl view, ViewDelta viewElement)
   at Avalonia.FuncUI.VirtualDom.Patcher.create(ViewDelta viewElement)
   at Avalonia.FuncUI.VirtualDom.Patcher.patch_avalonia@162(IControl view, FSharpOption`1 viewElement, AvaloniaProperty property)
   at Avalonia.FuncUI.VirtualDom.Patcher.patchContentSingle(IControl view, Accessor accessor, FSharpOption`1 viewElement)
   at Avalonia.FuncUI.VirtualDom.Patcher.patch(IControl view, ViewDelta viewElement)
   at Avalonia.FuncUI.VirtualDom.Patcher.create(ViewDelta viewElement)
   at Avalonia.FuncUI.VirtualDom.Patcher.patch_IList@86-1.Invoke(Int32 index, ViewDelta viewElement)
   at Microsoft.FSharp.Collections.SeqModule.IterateIndexed[T](FSharpFunc`2 action, IEnumerable`1 source) in D:\a\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 523
   at Avalonia.FuncUI.VirtualDom.Patcher.patch_IList@82(FSharpList`1 delta, IList collection)
   at Avalonia.FuncUI.VirtualDom.Patcher.patch(IControl view, ViewDelta viewElement)
   at Avalonia.FuncUI.VirtualDom.Patcher.create(ViewDelta viewElement)
   at Avalonia.FuncUI.VirtualDom.Patcher.patch_avalonia@162(IControl view, FSharpOption`1 viewElement, AvaloniaProperty property)
   at Avalonia.FuncUI.VirtualDom.Patcher.patchContentSingle(IControl view, Accessor accessor, FSharpOption`1 viewElement)
   at Avalonia.FuncUI.VirtualDom.Patcher.patch(IControl view, ViewDelta viewElement)
   at Avalonia.FuncUI.VirtualDom.Patcher.create(ViewDelta viewElement)
   at Avalonia.FuncUI.VirtualDom.Patcher.patch_IList@86-1.Invoke(Int32 index, ViewDelta viewElement)
   at Microsoft.FSharp.Collections.SeqModule.IterateIndexed[T](FSharpFunc`2 action, IEnumerable`1 source) in D:\a\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 523
   at Avalonia.FuncUI.VirtualDom.Patcher.patch_IList@82(FSharpList`1 delta, IList collection)
   at Avalonia.FuncUI.VirtualDom.Patcher.patch(IControl view, ViewDelta viewElement)
   at Avalonia.FuncUI.VirtualDom.Patcher.create(ViewDelta viewElement)
   at Avalonia.FuncUI.VirtualDom.Patcher.patch_avalonia@162(IControl view, FSharpOption`1 viewElement, AvaloniaProperty property)
   at Avalonia.FuncUI.VirtualDom.Patcher.patchContentSingle(IControl view, Accessor accessor, FSharpOption`1 viewElement)
   at Avalonia.FuncUI.VirtualDom.Patcher.patch(IControl view, ViewDelta viewElement)
   at Avalonia.FuncUI.VirtualDom.Patcher.create(ViewDelta viewElement)
   at Avalonia.FuncUI.VirtualDom.Patcher.patch_IList@86-1.Invoke(Int32 index, ViewDelta viewElement)
   at Microsoft.FSharp.Collections.SeqModule.IterateIndexed[T](FSharpFunc`2 action, IEnumerable`1 source) in D:\a\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 523
   at Avalonia.FuncUI.VirtualDom.Patcher.patch_IList@82(FSharpList`1 delta, IList collection)
   at Avalonia.FuncUI.VirtualDom.Patcher.patch(IControl view, ViewDelta viewElement)
   at Avalonia.FuncUI.VirtualDom.Patcher.create(ViewDelta viewElement)
   at Avalonia.FuncUI.VirtualDom.VirtualDom.updateRoot(IContentControl host, FSharpOption`1 last, FSharpOption`1 next)
   at Avalonia.FuncUI.Components.Hosts.HostWindow.update(FSharpOption`1 nextViewElement)
   at Avalonia.FuncUI.Components.Hosts.HostWindow.Avalonia.FuncUI.Components.Hosts.IViewHost.Update(FSharpOption`1 next)
   at Avalonia.FuncUI.Elmish.Program.setState@22.Invoke(model state, FSharpFunc`2 dispatch)
   at Elmish.ProgramModule.runWith[arg,model,msg,view](arg arg, Program`4 program)
   at Gui.Shell.MainWindow..ctor() in /Users/tommy/Programming/flower-gui-fsharp/Gui/Shell.fs:line 540
   at Gui.App.OnFrameworkInitializationCompleted() in /Users/tommy/Programming/flower-gui-fsharp/Gui/Program.fs:line 22
   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 312
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 179
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 208
   at Gui.Program.main(String[] args) in /Users/tommy/Programming/flower-gui-fsharp/Gui/Program.fs:line 29
```

**Comment by JaggerJo** [comment]
> Unhandled exception. System.MissingMethodException: Cannot dynamically create an instance of type 'Avalonia.Svg.Skia.Svg'. Reason: No parameterless constructor defined.

You are trying to create an instance of `Svg` without passing any parameters to the activator. `Svg` has no constructors that take 0 parameters. This is why it fails. 

You need to create an `IView` that contains constructor parameters. 

<img width="805" alt="image" src="https://user-images.githubusercontent.com/13090415/159954973-7e405eb4-3314-416b-9953-fe93a12afba3.png">

You could add an extension to the ViewBuilder to make that simple. 

```fsharp
type ViewBuilder with

    static member Create<'view>(attrs: IAttr<'view> list, constructorArgs: obj array) : IView<'view> =
        { View.ViewType = typeof<'view>
          View.ViewKey = ValueNone
          View.Attrs = attrs
          View.ConstructorArgs = constructorArgs
          View.Outlet = ValueNone }
        :> IView<'view>
```
