### ISSUE TITLE
Avalonia.FuncUI.Elmish is incompatible with Elmish 4

### ISSUE THREAD

**Issue by vincentremond** [fsprojects/Avalonia.FuncUI#240]
The method `withSyncDispatch` seems to have been removed in Elmish 4.
But the package `Avalonia.FuncUI.Elmish` [seems to rely on it](https://github.com/fsprojects/Avalonia.FuncUI/blob/master/src/Avalonia.FuncUI.Elmish/Library.fs#L31).

At runtime I get this error : 
```
Unhandled exception. System.MissingMethodException: Method not found: 'Elmish.Program`4<System.__Canon,System.__Canon,System.__Canon,System.__Canon> Elmish.ProgramModule.withSyncDispatch(Microsoft.FSharp.Core.FSharpFunc`2<Microsoft.FSharp.Core.FSharpFunc`2<System.__Canon,Microsoft.FSharp.Core.Unit>,Microsoft.FSharp.Core.FSharpFunc`2<System.__Canon,Microsoft.FSharp.Core.Unit>>, Elmish.Program`4<System.__Canon,System.__Canon,System.__Canon,System.__Canon>)'.
   at Avalonia.FuncUI.Elmish.Program.withHost[arg,model,msg,a](IViewHost host, Program`4 program)
   at HueModoro.Shell.MainWindow..ctor() in D:\XXX\Shell.fs:line 86
   at HueModoro.App.OnFrameworkInitializationCompleted() in D:\XXX\Program.fs:line 21
   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 312
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 179
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 208
   at HueModoro.Program.main(String[] args) in D:\XXX\Program.fs:line 28
   ```

**Comment by JordanMarr** [comment]
Thanks for posting the issue. 
I am looking into this as well as other Elmish 4 changes today.

**Comment by JordanMarr** [comment]
The latest prerelease (available now) has been upgraded to Elmish v4. 

https://github.com/fsprojects/Avalonia.FuncUI/pull/248
