### ISSUE TITLE
'Getting Started' page example counter app fails to run: Missing Field 'TextProperty'

### ISSUE THREAD

**Issue by clembu** [fsprojects/Avalonia.FuncUI#287]
### Error description

The getting started simple counter example fails at runtime. I don't know if I've installed the wrong version of something, or if I'm missing some visual studio feature, but I'm getting `Missing Field` exceptions.

#### Steps to error:
1) created new F# "Console App" targetting .net7
2) added the nuget packages mentioned in 'package versions' below
3) replaced the `Program.fs` code with that from https://funcui.avaloniaui.net/ 
4) ran the program

#### The error

An uncaught exception is thrown from `Textblock.text`, see 'stack trace' below

#### Package versions:
- `Avalonia.FuncUI` : `0.6.0-preview9`
- `Avalonia.Desktop` : `11.0.0-preview6`
- `Avalonia.Themes.Fluent` : `11.0.0-preview6`

#### Stack trace
```
System.MissingFieldException
  HResult=0x80131511
  Message=Field not found: 'Avalonia.Controls.TextBlock.TextProperty'.
  Source=Avalonia.FuncUI
  StackTrace:
   at Avalonia.FuncUI.DSL.TextBlock.TextBlock.text.Static[t](String value)
   at Program.Main.view@14.Invoke(IComponentContext ctx) in H:\dev\apps\Filegraph.Elmish\Filegraph\Program.fs:line 17
   at <StartupCode$Avalonia-FuncUI>.$Component.Update@24.Invoke()
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run() in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 205
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 38
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 270
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 215
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 62
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 123
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 214
   at Program.Program.main(String[] args) in H:\dev\apps\Filegraph.Elmish\Filegraph\Program.fs:line 67
```

**Comment by JaggerJo** [comment]
The current preview release of FuncUI supports Avalonia 11.0.0-preview5. There are breaking changes between preview versions - preview 6 is not supported yet.
